// <auto-generated />
using System;
using Bingo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bingo.Infrastructure.Migrations
{
    [DbContext(typeof(BingoDbContext))]
    partial class BingoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bingo.Domain.Entities.DailyAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("GameDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsBusted")
                        .HasColumnType("boolean");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("SimUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("StartingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TicketsBought")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPayout")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalStaked")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SimUserId", "GameDate")
                        .IsUnique();

                    b.ToTable("daily_accounts", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Entities.Draw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("D1")
                        .HasColumnType("integer");

                    b.Property<int>("D2")
                        .HasColumnType("integer");

                    b.Property<int>("D3")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DrawAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTriple")
                        .HasColumnType("boolean");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Sum")
                        .HasColumnType("integer");

                    b.Property<int?>("TripleDigit")
                        .HasColumnType("integer");

                    b.Property<string>("WinningResult")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasIndex("DrawAt")
                        .IsUnique();

                    b.ToTable("draws", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Entities.PrizeRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BetKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("BetValue")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("BetKind", "BetValue")
                        .IsUnique();

                    b.ToTable("prize_rules", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Entities.SimUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StrategyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyKey");

                    b.ToTable("sim_users", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Entities.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultParamsJson")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdaptive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("strategies", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Entities.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BetKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("BetValue")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("DailyAccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DrawId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWin")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal>("Payout")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Profit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SimUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Stake")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("TargetDrawAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DailyAccountId");

                    b.HasIndex("DrawId");

                    b.HasIndex("IsSettled");

                    b.HasIndex("SimUserId", "TargetDrawAt");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Entities.UserStat", b =>
                {
                    b.Property<int>("SimUserId")
                        .HasColumnType("integer");

                    b.Property<int>("DaysBusted")
                        .HasColumnType("integer");

                    b.Property<int>("DaysPlayed")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetProfit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Roi")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("TotalPayout")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalStaked")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.HasKey("SimUserId");

                    b.ToTable("user_stats", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Entities.UserStrategyState", b =>
                {
                    b.Property<int>("SimUserId")
                        .HasColumnType("integer");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SimUserId");

                    b.ToTable("user_strategy_states", (string)null);
                });

            modelBuilder.Entity("Bingo.Domain.Entities.DailyAccount", b =>
                {
                    b.HasOne("Bingo.Domain.Entities.SimUser", "SimUser")
                        .WithMany()
                        .HasForeignKey("SimUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimUser");
                });

            modelBuilder.Entity("Bingo.Domain.Entities.SimUser", b =>
                {
                    b.HasOne("Bingo.Domain.Entities.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyKey")
                        .HasPrincipalKey("Key")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("Bingo.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Bingo.Domain.Entities.DailyAccount", "DailyAccount")
                        .WithMany()
                        .HasForeignKey("DailyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bingo.Domain.Entities.Draw", "Draw")
                        .WithMany()
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bingo.Domain.Entities.SimUser", "SimUser")
                        .WithMany()
                        .HasForeignKey("SimUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyAccount");

                    b.Navigation("Draw");

                    b.Navigation("SimUser");
                });

            modelBuilder.Entity("Bingo.Domain.Entities.UserStat", b =>
                {
                    b.HasOne("Bingo.Domain.Entities.SimUser", "SimUser")
                        .WithMany()
                        .HasForeignKey("SimUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimUser");
                });

            modelBuilder.Entity("Bingo.Domain.Entities.UserStrategyState", b =>
                {
                    b.HasOne("Bingo.Domain.Entities.SimUser", "SimUser")
                        .WithMany()
                        .HasForeignKey("SimUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimUser");
                });
#pragma warning restore 612, 618
        }
    }
}
